#obj-$(CONFIG_MS_SCL_INFINITY3) +=  ../../hal/infinity3/scl/
#obj-$(CONFIG_MS_SCL_INFINITY3) +=  ../../hal/cleveland/scl/
obj-$(CONFIG_MS_SCL_INFINITY2) +=  ../../hal/infinity2/scl/
obj-$(CONFIG_MS_SCL_INFINITY3) +=  ../../hal/infinity2/scl/
#obj-$(CONFIG_MS_SCL_CLEVELAND) +=  ../../hal/cleveland/scl/