cmd_/home/wenshuai.xi/SI/alkaid/sdk/mhal/k6l/module.o := arm-buildroot-linux-uclibcgnueabi-gcc -Wp,-MD,/home/wenshuai.xi/SI/alkaid/sdk/mhal/k6l/.module.o.d -nostdinc -isystem /opt/arm_4.7.2_with_fortify/bin/../lib/gcc/arm-buildroot-linux-uclibcgnueabi/4.7.2/include -I/home/wenshuai.xi/SI/alkaid/project/kbuild/3.10.40/arch/arm/include -Iarch/arm/include/generated -Iinclude -I/home/wenshuai.xi/SI/alkaid/project/kbuild/3.10.40/arch/arm/include/uapi -Iarch/arm/include/generated/uapi -I/home/wenshuai.xi/SI/alkaid/project/kbuild/3.10.40/include/uapi -Iinclude/generated/uapi -include /home/wenshuai.xi/SI/alkaid/project/kbuild/3.10.40/include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Iarch/arm/include -Idrivers/mstar2 -Iarch/arm/arm-boards/generic/include/ -Iarch/arm/arm-boards/../../../../mstar2/hal/k6lite/cpu//include -Iarch/arm/arm-boards/plat-mstar//include -Iarch/arm/arm-boards/../../../../mstar2/hal/k6lite/cpu/ -Iarch/arm/arm-boards/plat-mstar/ -Idrivers/mstar -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -fno-peephole2 -O2 -g -fconserve-stack -fno-dwarf2-cfi-asm -fno-omit-frame-pointer -mapcs -mno-sched-prolog -fstack-protector -fno-conserve-stack -mabi=aapcs-linux -mno-thumb-interwork -marm -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -Wframe-larger-than=1024 -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -DMODULE -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(module)" -D"KBUILD_MODNAME=KBUILD_STR(mhal)" -I/home/wenshuai.xi/SI/alkaid/project/kbuild/3.10.40/mstar2/configs/k6l/include  -c -o /home/wenshuai.xi/SI/alkaid/sdk/mhal/k6l/module.o /home/wenshuai.xi/SI/alkaid/sdk/mhal/k6l/module.c

source_/home/wenshuai.xi/SI/alkaid/sdk/mhal/k6l/module.o := /home/wenshuai.xi/SI/alkaid/sdk/mhal/k6l/module.c

deps_/home/wenshuai.xi/SI/alkaid/sdk/mhal/k6l/module.o := \

/home/wenshuai.xi/SI/alkaid/sdk/mhal/k6l/module.o: $(deps_/home/wenshuai.xi/SI/alkaid/sdk/mhal/k6l/module.o)

$(deps_/home/wenshuai.xi/SI/alkaid/sdk/mhal/k6l/module.o):
